version: '2'
services:
  # ----------------------
  # 1 - MySQL
  # ----------------------
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  # ----------------------
  # 2 - PhpMyAdmin
  # ----------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 10085:80
    environment:
      PMA_HOST: mysql

  # ----------------------
  # 3 - Composer
  # ----------------------
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    depends_on:
      - mysql
    volumes:
      - ./back:/var/www/back/
      - vendor:/var/www/back/vendor

  # ----------------------
  # 4 - PHP7.2+Apache2.4
  # ----------------------
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    expose:
      - 80
      - 8080
    ports:
      - 10081:80
      - 10082:8080
    depends_on:
      - mysql
      - composer
    volumes:
      - ./back:/var/www/back/
      - vendor:/var/www/back/vendor

  # ----------------------
  # 5 - Nginx
  # ----------------------
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    expose:
    - 3000
    ports:
    - 10083:3000
    depends_on:
    - back
    volumes:
    - ./front:/app
volumes:
  db:
  vendor:
    driver: local