FROM php:7.2-apache

ENV DEBIAN_FRONTEND noninteractive

# Installation de Curl, Git (nécessaire pour l'installation de symfony/polyfill-mbstring) et Composer
RUN apt-get update \
    && apt-get install -y curl git \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Configuration d'Apache
RUN a2enmod rewrite \
    && echo 'ServerName localhost' >> /etc/apache2/apache2.conf

# Installation des extentions pdo et pdo_mysql
RUN docker-php-ext-install pdo pdo_mysql

# Ajout du VirtualHost
ADD docker/back/dev/000-default.conf /etc/apache2/sites-available/000-default.conf

# On expose le port 80 de ce conteneur
EXPOSE 80