version: '2'
services:
  # ----------------------
  # 1 - MySQL
  # ----------------------
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
  # ----------------------
  # 2 - Composer
  # ----------------------
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    volumes:
      - ./back:/var/www/back/
      - vendor:/var/www/back/vendor
    depends_on:
      - database
  # ----------------------
  # 3 - PHP7.2+Apache2.4
  # ----------------------
  back:
    build:
      context: .
      dockerfile: Dockerfile.back
    expose:
      - 80
      - 8080
    ports:
      - '81:80'
      - '82:8080'
    depends_on:
      - database
      - composer
    volumes:
      - ./back:/var/www/back/
      - vendor:/var/www/back/vendor
volumes:
  db:
  vendor: