#!/bin/bash

# On vérifie si Docker est installé
command -v docker >/dev/null 2>&1 || {
	echo "Veuillez installer Docker : https://docs.docker.com/install/"
	exit 1;
}

# On execute le script Yarn sur le conteneur "Nginx"
docker exec -it $(docker container ls --filter name=rested_front --quiet) yarn "$*"